import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingLeft: 40,
    paddingRight: 40,
    paddingBottom: 100,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#0b0d12",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
    borderBottom: "1px solid #e6e8ee",
    paddingBottom: 12,
  },
  logoRow: { flexDirection: "row", alignItems: "center" },
  brand: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#2f6fed", letterSpacing: 0.4, marginLeft: 7 },
  brandSuffix: { fontSize: 9.5, fontFamily: "Helvetica", color: "#565c68", letterSpacing: 0 },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#565c68", marginBottom: 20 },
  scoreBox: { alignItems: "center" },
  scoreValue: { fontSize: 22, fontFamily: "Helvetica-Bold", color: "#2f6fed" },
  scoreLabel: { fontSize: 8, color: "#565c68" },
  section: { marginBottom: 14 },
  sectionTitle: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: "#565c68",
    marginBottom: 4,
  },
  grid2: { flexDirection: "row" },
  col: { flex: 1, paddingRight: 16 },
  text: { fontSize: 10, lineHeight: 1.5 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  rowLabel: { fontSize: 9, color: "#565c68" },
  rowValue: { fontSize: 10, fontFamily: "Helvetica-Bold" },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    borderTop: "1px solid #e6e8ee",
    paddingTop: 10,
  },
  footerBrandRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5, marginBottom: 3 },
  footerBrand: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#2f6fed",
    letterSpacing: 0.3,
  },
  footerSlogan: { fontSize: 7.5, color: "#565c68", letterSpacing: 0.2, marginBottom: 3 },
  footerLegal: { fontSize: 7, color: "#8a909c", marginBottom: 3 },
  footerMeta: { fontSize: 7.5, color: "#8a909c" },
  signatureBox: {
    marginTop: 24,
    borderTop: "1px solid #e6e8ee",
    paddingTop: 12,
  },
});
