import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#0b0d12" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    borderBottom: "1px solid #e6e8ee",
    paddingBottom: 16,
  },
  logoRow: { flexDirection: "row", alignItems: "center" },
  brand: { fontSize: 14, fontFamily: "Helvetica-Bold", color: "#0b0d12", marginLeft: 8 },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#565c68", marginBottom: 20 },
  scoreBox: { alignItems: "center" },
  scoreValue: { fontSize: 22, fontFamily: "Helvetica-Bold", color: "#2f6fed" },
  scoreLabel: { fontSize: 8, color: "#565c68" },
  section: { marginBottom: 14 },
  sectionTitle: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: "#565c68",
    marginBottom: 4,
  },
  grid2: { flexDirection: "row" },
  col: { flex: 1, paddingRight: 16 },
  text: { fontSize: 10, lineHeight: 1.5 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  rowLabel: { fontSize: 9, color: "#565c68" },
  rowValue: { fontSize: 10, fontFamily: "Helvetica-Bold" },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#8a909c",
    textAlign: "center",
    borderTop: "1px solid #e6e8ee",
    paddingTop: 10,
  },
  signatureBox: {
    marginTop: 24,
    borderTop: "1px solid #e6e8ee",
    paddingTop: 12,
  },
});
